name: EasyCommandAutofill
main: jasonwynn10\EasyCommandAutofill\Main
version: 1.0.5
api: 3.0.0
mcpe-protocol:
 - 389
 - 390
 - 407
 - 408
 - 419
 - 422
 - 428
description: "A plugin which adds commands to the client's autofill by parsing usage messages"
author: "jasonwynn10"