name: EasyCommandAutofill
main: jasonwynn10\EasyCommandAutofill\Main
version: 1.0.0-beta1
api: 3.0.0
mcpe-protocol:
 - 389
 - 390
 - 407
description: "A plugin which adds commands to the client's autofill by parsing usage messages"
author: "jasonwynn10"
